"""
    Whop API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.10
    Contact: support@whop.com
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from whopclient.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from whopclient.exceptions import ApiAttributeError


def lazy_import():
    from whopclient.model.license_discord import LicenseDiscord
    from whopclient.model.license_plan import LicensePlan
    from whopclient.model.license_twitter import LicenseTwitter
    from whopclient.model.metadata import Metadata
    globals()['LicenseDiscord'] = LicenseDiscord
    globals()['LicensePlan'] = LicensePlan
    globals()['LicenseTwitter'] = LicenseTwitter
    globals()['Metadata'] = Metadata


class License(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
        ('key_status',): {
            'None': None,
            'PENDING': "pending",
            'APPROVED': "approved",
            'LISTED': "listed",
            'REMOVED': "removed",
            'SOLD': "sold",
            'TERMINATED': "terminated",
            'EXPIRED': "expired",
            'DISABLED': "disabled",
        },
        ('subscription_status',): {
            'None': None,
            'COMPLETED': "completed",
            'ACTIVE': "active",
            'TRIALING': "trialing",
            'CANCELED': "canceled",
        },
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = True

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'id': (int, none_type,),  # noqa: E501
            'key': (str, none_type,),  # noqa: E501
            'rental_key': (str, none_type,),  # noqa: E501
            'rented': (bool, none_type,),  # noqa: E501
            'rental_end': (str, none_type,),  # noqa: E501
            'valid': (bool, none_type,),  # noqa: E501
            'key_status': (str, none_type,),  # noqa: E501
            'subscription_status': (str, none_type,),  # noqa: E501
            'quantity': (int, none_type,),  # noqa: E501
            'banned': (bool, none_type,),  # noqa: E501
            'metadata': (Metadata,),  # noqa: E501
            'next_renewal_date': (str, none_type,),  # noqa: E501
            'renewal_period': (int, none_type,),  # noqa: E501
            'created_at': (str, none_type,),  # noqa: E501
            'discord': (LicenseDiscord,),  # noqa: E501
            'twitter': (LicenseTwitter,),  # noqa: E501
            'is_scammer': (bool, date, datetime, dict, float, int, list, str, none_type,),  # noqa: E501
            'plan': (LicensePlan,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'id': 'id',  # noqa: E501
        'key': 'key',  # noqa: E501
        'rental_key': 'rental_key',  # noqa: E501
        'rented': 'rented',  # noqa: E501
        'rental_end': 'rental_end',  # noqa: E501
        'valid': 'valid',  # noqa: E501
        'key_status': 'key_status',  # noqa: E501
        'subscription_status': 'subscription_status',  # noqa: E501
        'quantity': 'quantity',  # noqa: E501
        'banned': 'banned',  # noqa: E501
        'metadata': 'metadata',  # noqa: E501
        'next_renewal_date': 'next_renewal_date',  # noqa: E501
        'renewal_period': 'renewal_period',  # noqa: E501
        'created_at': 'created_at',  # noqa: E501
        'discord': 'discord',  # noqa: E501
        'twitter': 'twitter',  # noqa: E501
        'is_scammer': 'is_scammer',  # noqa: E501
        'plan': 'plan',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):  # noqa: E501
        """License - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            id (int, none_type): [optional]  # noqa: E501
            key (str, none_type): [optional]  # noqa: E501
            rental_key (str, none_type): [optional]  # noqa: E501
            rented (bool, none_type): [optional]  # noqa: E501
            rental_end (str, none_type): [optional]  # noqa: E501
            valid (bool, none_type): [optional]  # noqa: E501
            key_status (str, none_type): [optional]  # noqa: E501
            subscription_status (str, none_type): [optional]  # noqa: E501
            quantity (int, none_type): [optional]  # noqa: E501
            banned (bool, none_type): [optional]  # noqa: E501
            metadata (Metadata): [optional]  # noqa: E501
            next_renewal_date (str, none_type): [optional]  # noqa: E501
            renewal_period (int, none_type): [optional]  # noqa: E501
            created_at (str, none_type): [optional]  # noqa: E501
            discord (LicenseDiscord): [optional]  # noqa: E501
            twitter (LicenseTwitter): [optional]  # noqa: E501
            is_scammer (bool, date, datetime, dict, float, int, list, str, none_type): [optional]  # noqa: E501
            plan (LicensePlan): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """License - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            id (int, none_type): [optional]  # noqa: E501
            key (str, none_type): [optional]  # noqa: E501
            rental_key (str, none_type): [optional]  # noqa: E501
            rented (bool, none_type): [optional]  # noqa: E501
            rental_end (str, none_type): [optional]  # noqa: E501
            valid (bool, none_type): [optional]  # noqa: E501
            key_status (str, none_type): [optional]  # noqa: E501
            subscription_status (str, none_type): [optional]  # noqa: E501
            quantity (int, none_type): [optional]  # noqa: E501
            banned (bool, none_type): [optional]  # noqa: E501
            metadata (Metadata): [optional]  # noqa: E501
            next_renewal_date (str, none_type): [optional]  # noqa: E501
            renewal_period (int, none_type): [optional]  # noqa: E501
            created_at (str, none_type): [optional]  # noqa: E501
            discord (LicenseDiscord): [optional]  # noqa: E501
            twitter (LicenseTwitter): [optional]  # noqa: E501
            is_scammer (bool, date, datetime, dict, float, int, list, str, none_type): [optional]  # noqa: E501
            plan (LicensePlan): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
